name: cod
version: 0.1.0.0
github: "MoritzR/CurseOfDestiny"
license: GNU
author: "Moritz Rumpf"
# maintainer:          "example@example.com"
copyright: "2020 Moritz Rumpf"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/MoritzR/CurseOfDestiny#readme>

dependencies:
  - base >= 4.7 && < 5
  - lens
  - polysemy
  - polysemy-plugin
  - generic-lens

ghc-options:
  - -fplugin=Polysemy.Plugin # for type inference and performance, according to https://github.com/polysemy-research/polysemy#overview
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively

default-extensions:
  - ImportQualifiedPost
  # generic-lens required extensions
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - NoMonomorphismRestriction
  - TypeApplications
  # for usage of the '#label' notation
  - OverloadedLabels
  # PolySemy required extensions
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies

library:
  source-dirs: src

executables:
  cod-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cod

tests:
  cod-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cod
      - hspec
