name:                cod
version:             0.1.0.0
github:              "https://github.com/MoritzR/CurseOfDestiny"
license:             GNU
author:              "Moritz Rumpf"
# maintainer:          "example@example.com"
copyright:           "2020 Moritz Rumpf"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MoritzR/CurseOfDestiny#readme>

dependencies:
- base >= 4.7 && < 5
- lens  

library:
  source-dirs: src

executables:
  cod-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cod

tests:
  cod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cod
    - hspec
